In [9]:
from keras.src.legacy.preprocessing.text import one_hot

In [10]:


        sent = ['the glass of milk',
                'the glass of juice',
                'the cup of tea',
                'I am good boy',
                'I am good developer',
                'understand the meaning of words',
                ' your videos are good']

        sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'I am good developer',
 'understand the meaning of words',
 ' your videos are good']

In [11]:
#define the vocabulary size
voc_size = 10000


In [12]:
#one hot representations
one_hot_reper= [one_hot(word, voc_size) for word in sent]
print(one_hot_reper)

[[9347, 5314, 1980, 4280], [9347, 5314, 1980, 9436], [9347, 5285, 1980, 9796], [2634, 6155, 2850, 515], [2634, 6155, 2850, 6525], [4312, 9347, 9655, 1980, 8610], [2706, 1535, 4833, 2850]]


In [15]:
# word Emdedding Representation

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

In [16]:
import numpy as np

In [17]:
sent_length = 8  # max length

embeded_doc = pad_sequences(one_hot_reper, padding='pre',maxlen=sent_length)
print(embeded_doc)


""" in one hot we didn't get the same dimensions, so we can you pad_sequences to make the equal dimensions"""

[[   0    0    0    0 9347 5314 1980 4280]
 [   0    0    0    0 9347 5314 1980 9436]
 [   0    0    0    0 9347 5285 1980 9796]
 [   0    0    0    0 2634 6155 2850  515]
 [   0    0    0    0 2634 6155 2850 6525]
 [   0    0    0 4312 9347 9655 1980 8610]
 [   0    0    0    0 2706 1535 4833 2850]]


In [18]:
#feature representation
dim=10


In [19]:
model =Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam', 'mse')

D:\GENAI\RNN Project Implementation\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embeded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[[-0.0431775 , -0.01770132, -0.03291719,  0.03966708,
          0.04887617,  0.04265114, -0.0152854 ,  0.04048708,
          0.01606866,  0.01747881],
        [-0.0431775 , -0.01770132, -0.03291719,  0.03966708,
          0.04887617,  0.04265114, -0.0152854 ,  0.04048708,
          0.01606866,  0.01747881],
        [-0.0431775 , -0.01770132, -0.03291719,  0.03966708,
          0.04887617,  0.04265114, -0.0152854 ,  0.04048708,
          0.01606866,  0.01747881],
        [-0.0431775 , -0.01770132, -0.03291719,  0.03966708,
          0.04887617,  0.04265114, -0.0152854 ,  0.04048708,
          0.01606866,  0.01747881],
        [ 0.02822487, -0.03119757, -0.01785787, -0.01484948,
         -0.01323342, -0.01603163, -0.01366061, -0.04036904,
          0.0016688 , -0.00677736],
        [ 0.02531625,  0.00704206, -0.0450323 , -0.02495441,
         -0.00229318, -0.049315  ,  0.02178686, -0.04117502,
         -0.03285559,  0.04788486],
        [ 0.00463861,  0.03893608, -0.04386604, -0.0